SELECT 
	emp.EMPL_NAME, emp.EMPL_JOB_ID, emp.EMPL_SALARY
FROM EMPL AS emp
JOIN (
	SELECT EMPL_JOB_ID, MAX(EMPL_SALARY) AS HighestSalary
	FROM EMPL
	GROUP BY EMPL_JOB_ID
) AS subemp ON emp.EMPL_JOB_ID = subemp.EMPL_JOB_ID AND emp.EMPL_SALARY = subemp.HighestSalary
ORDER BY emp.EMPL_SALARY DESC
