SELECT
	cab.KODE_CABANG,
	cab.NAMA_CABANG,
	cab.KODE_AREA,
	CASE 
		WHEN cab.KODE_AREA = 0001 THEN 'AREA JABODETABEK'
		WHEN cab.KODE_AREA = 0002 THEN 'AREA JABAR'
		WHEN cab.KODE_AREA = 0003 THEN 'AREA JATENG'
		WHEN cab.KODE_AREA = 0004 THEN 'AREA JATIM'
		ELSE 'AREA BEKASI'
	END AS NAMA_AREA
FROM
	MASTER_CABANG AS cab
