SELECT	
	cab.KODE_CABANG,
	cab.NAMA_CABANG,
	COUNT(trans.NOMOR_KONTRAK) AS TOTAL_KONTRAK
FROM
	MASTER_CABANG AS cab
JOIN
	TRANS_CUST AS trans ON cab.KODE_CABANG = trans.KODE_CABANG
GROUP BY cab.KODE_CABANG, cab.NAMA_CABANG
