SELECT
	MONTH(trans.TANGGAL_TRANSAKSI) AS MONTH,
	YEAR(trans.TANGGAL_TRANSAKSI) AS YEAR,
	COUNT(NOMOR_KONTRAK) AS TOTAL_KONTRAK
FROM
	TRANS_CUST AS trans
WHERE 
	YEAR(trans.TANGGAL_TRANSAKSI) = 2015
GROUP BY 
	MONTH(trans.TANGGAL_TRANSAKSI),
	YEAR(trans.TANGGAL_TRANSAKSI)
ORDER BY 
	MONTH(trans.TANGGAL_TRANSAKSI)
