SELECT
	trans.KODE_CABANG,
	cab.NAMA_CABANG,
	cus.KODE_NASABAH,
	cus.NAMA_NASABAH,
	trans.HARGA_UNIT,
	trans.TANGGAL_TRANSAKSI
FROM
	TRANS_CUST AS trans
JOIN	
	MASTER_CUST AS cus ON trans.KODE_NASABAH = cus.KODE_NASABAH
JOIN
	MASTER_CABANG AS cab ON cus.KODE_CABANG = cab.KODE_CABANG
