SELECT
	cus.KODE_NASABAH,
	cus.NAMA_NASABAH,
	cus.KODE_CABANG,
	cab.NAMA_CABANG,
	CASE 
		WHEN cab.KODE_AREA = 0001 THEN 'AREA JABODETABEK'
		WHEN cab.KODE_AREA = 0002 THEN 'AREA JABAR'
		WHEN cab.KODE_AREA = 0003 THEN 'AREA JATENG'
		WHEN cab.KODE_AREA = 0004 THEN 'AREA JATIM'
		ELSE 'AREA BEKASI'
	END AS NAMA_AREA
FROM
	MASTER_CUST AS cus
JOIN
	MASTER_CABANG AS cab ON cus.KODE_CABANG = cab.KODE_CABANG
